[package]
name = "mechvibes-cli"
version = "0.4.0"
edition = "2024"

[[bin]]
name = "mechvibes-cli"
path = "src/main.rs"

[dependencies]
mechvibes-core = { path = "../mechvibes-core" }

crossbeam-channel = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

clap = { version = "4", features = ["derive"] }
ctrlc = { version = "3", features = ["termination"] }

[target.'cfg(windows)'.dependencies]
tray-icon = "0.14"
image = "0.24"
winapi = { version = "0.3", features = ["winuser"] }
